export const PATIENT_REQUEST = 'PATIENT_REQUEST';
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS';
export const PATIENT_FAILURE = 'PATIENT_FAILURE';
export const PATIENT_POST = 'PATIENT_POST';

// delete
export const PATIENT_DELETE_REQUEST = 'PATIENT_DELETE_REQUEST';
export const PATIENT_DELETE_SUCCESS = 'PATIENT_DELETE_SUCCESS';
export const PATIENT_DELETE_FAILURE = 'PATIENT_DELETE_FAILURE';

